#!/usr/bin/env bash

download=true
search_term=$1
while test $# -gt 1
do
    case "$1" in
        --no-download) download=false
            ;;
        --opt2) echo "option 2"
            ;;
        --*) echo "bad option $1"
            ;;
        *) echo "argument $1"
            ;;
    esac
    shift
done

UNSPLASH_DIR="$HOME/.local/share/unsplash"

DATE=$(date +"%A, %B %-d")
# WEATHER=$(curl wttr.in?format="+%c+%t")

ringcolor=FFFFFFFF
insidecolor=00000000
linecolor=00000000
separatorcolor=00000000

ringvercolor=00000000
insidevercolor=f1c40fff

ringwrongcolor=c0392bff
insidewrongcolor=00000000

keyhlcolor=AAAAAAFF
bshlcolor=AAAAAAFF


i3lock -t -i "$UNSPLASH_DIR"/image.png \
    --clock --force-clock --timepos="w/2:h/2" --timesize=96 --timecolor=FFFFFFFF \
    --datestr="$DATE" --datepos="tx:ty+80" --datesize=32 --datecolor=FFFFFFFF \
    --indpos="w/2-r/2:h-r*2" --radius 20 \
    --ringcolor=$ringcolor --insidecolor=$insidecolor --linecolor=$linecolor \
    --separatorcolor=$separatorcolor --ringvercolor=$ringvercolor \
    --insidevercolor=$insidevercolor --veriftext='' --ringwrongcolor=$ringwrongcolor \
    --insidewrongcolor=$insidewrongcolor --wrongtext='' --keyhlcolor=$keyhlcolor \
    --bshlcolor=$bshlcolor --noinputtext=''

if ping -q -c 1 -W 1 8.8.8.8 >/dev/null && [ "$download" = true ]; then
    unsplash "$searchterm" > $HOME/.local/share/unsplash/log 2>&1 && notify-send "New Lock Wallpaper Downloaded"
fi
